### ISSUE TITLE
`RangeError` in README example

### ISSUE THREAD

**Issue by JonasWanke** [marcelgarus/implicitly_animated_list#1]
Putting the example code from `README.md` in an otherwise empty `MaterialPageRoute` results in an error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack
#0      List.[]  (dart:core-patch/growable_array.dart:149:60)
#1      _ImplicitlyAnimatedListState.build.<anonymous closure>  (package:implicitly_animated_list/implicitly_animated_list.dart:121:52)
#2      SliverAnimatedListState._itemBuilder 
package:flutter/…/widgets/animated_list.dart:983
#3      SliverChildBuilderDelegate.build 
package:flutter/…/widgets/sliver.dart:446
#4      SliverMultiBoxAdaptorElement._build.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1260
...
════════════════════════════════════════════════════════════════════════════════
```

After hot reloading, the four `ListTile`s at least show up, but there's still an error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
RangeError (index): Invalid value: Not in range 0..3, inclusive: 4
════════════════════════════════════════════════════════════════════════════════
```

Seems like the first problem is fixed in a fork: https://github.com/Xenomer/implicitly_animated_list/commit/69a0f841fd0d022285e8cf7df4d83cba12687f30

**Comment by yokoboko** [comment]
I have the same problem. Any update on the issue?

**Comment by marcelgarus** [comment]
Sadly, I didn't have the time to look into this yet…

**Comment by mxzinke** [comment]
I made a PR, please have a look.

**Comment by marcelgarus** [comment]
I'll leave this open as a reminder for myself to test the code and publish the package.

**Comment by mxzinke** [comment]
Just found another bug, similar to this one. Occurring when you have an empty-List state and switching to a List with elements. 

I will do another PR. Sorry about inconvenience.

Should I open another Issue?

**Comment by marcelgarus** [comment]
Sure, feel welcome to open another PR.
There's no inconvenience, I'm always happy to merge better code.
